apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-logs
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.logs_storage_size }}
