server:
  servlet:
    context-path: /xtr-aeroport
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false  # Imposta su 'true' in un ambiente di produzione

  datasource:
    url: jdbc:h2:mem:volodb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    #    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
      encoding: UTF-8

xtr-aeroport:
  db:
    pagination:
      maxPageSize: 48

