version: '3'
services:
  app:
    container_name: linux-ojdk17-graal-aeroport
    image: artifactory.io/k8s-test/namespace/com.xtremealex/aeroport:linux-ojdk17-graal-aeroport
    build:
      context: ..
      dockerfile: docker/linux.Dockerfile
    ports:
      - "8080:8080"
