apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app_name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
        - image: {{ .Values.registry_target }}/{{ .Values.project_name }}/{{ .Values.app_name }}:{{ .Values.dockerTag }}
          name: {{ .Values.app_name }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.app_port }}
              name: {{ .Values.app_port_name }}
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.limit_cpu }}
              memory: {{ .Values.limit_memory }}
            requests:
              cpu: {{ .Values.request_cpu }}
              memory: {{ .Values.request_memory }}
          volumeMounts:
            - mountPath: /var/log/app
              name: vol-xxx-logs
          env:
            - name: HTTP_PORT
              value: {{ .Values.http_port }}
      imagePullSecrets:
        - name: {{ .Values.dockerRepository }}
      volumes:
        - name: vol-xxx-app-logs
          persistentVolumeClaim:
            claimName: app-logs
