apiVersion: v1
kind: Service
metadata:
  "helm.sh/hook": post-install,post-upgrade
  "helm.sh/hook-weight": "3"
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app_name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.app_port }}
      targetPort: {{ .Values.app_port }}
      protocol: TCP
      name: {{ .Values.app_port_name }}
  selector:
    app: {{ .Values.app_name }}