apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  "helm.sh/hook": post-install,post-upgrade
  "helm.sh/hook-weight": "4"
  name: {{ .Values.app_name }}
  annotations:
    ncp/ssl-mode: reencrypt
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.ingress_host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.app_name }}
                port:
                  number: {{ .Values.app_port }}
            path: /{{ .Values.app_name }}
            pathType: Prefix
